### ISSUE TITLE
Documentation does not render well in my browser

### ISSUE THREAD

**Issue by Sander3003** [OSGP/Documentation#20]
When I open the HTML version of the documentation. The index is missing, including some Icons.

![image](https://cloud.githubusercontent.com/assets/7427358/12138465/6be5952e-b459-11e5-963f-0dbfd66872f5.png)

@kevinsmeets do you have the same experience?

**Comment by Sander3003** [comment]
I used the chrome browser, IE does not show the index as well but shows the icons.

**Comment by kevinsmeets** [comment]
I found that using Google Chrome everything works fine, but I suspect that browser has some data cached...
Using Mozilla Firefox and Internet Explorer I have the same problem: the index is not shown.

The console of Mozilla Firefox shows that some font files and or icon files can't be downloaded from the server:
12:01:47.504 downloadable font: download not allowed (font-family: "Open Sans" style:normal weight:300 stretch:normal src index:1): content blocked source: http://54.77.62.182/job/OSGP_Documentation_development/lastSuccessfulBuild/artifact/_book/gitbook/fonts/opensans/300.woff1 style.css:1:23862

I'm not sure what causes this problem. Could be that recent updates for Jenkins make it harder to host an HTML site like this.

- I could try to host the site using Apache Webserver (instead of Jenkins) on the build server?
- Perhaps @Sander3003  has another place to host the documentation HTML site?

**Comment by Sander3003** [comment]
I will discuss this with @marcelvanhal and @phoutman.

**Comment by kevinsmeets** [comment]
Update: I have created a context (URL) in our Apache HTTPD Webserver's vhost. It seems that my hunch was sort of correct: when the GitBook website is hosted using Apache HTTPD the problem is not present. It looks like Jenkins has increased the security of the embedded Jetty webserver used by Jenkins.

@Sander3003 can you test if the problem is solved using this link: http://54.77.62.182/documentation

**Comment by Sander3003** [comment]
This new link works fine on all my browsers. Thanks.

**Comment by Sander3003** [comment]
Points http://54.77.62.182/documentation to the latest development documentation?

**Comment by Sander3003** [comment]
We need to change the links as well (e.g. in the documentation repository). I already change the link on  the OSGP website.

**Comment by kevinsmeets** [comment]
"Points http://54.77.62.182/documentation to the latest development documentation?" Yes

**Comment by kevinsmeets** [comment]
"We need to change the links as well (e.g. in the documentation repository). I already change the link on  the OSGP website." I already changed it.

Other links are:
http://54.77.62.182/documentation-pr (pull request build of documentation)
http://54.77.62.182/documentation-master (master-branch of documentation)
