### ISSUE TITLE
Unclear to me what needs to be done @ 3.3.14 Setting Up Apache Tomcat7 Server Context

### ISSUE THREAD

**Issue by Sander3003** [OSGP/Documentation#30]
Maybe we make this step more clear or refer to other relevant documentation?

**Comment by kevinsmeets** [comment]
One needs to copy the contents of the file context.xml to the file *Servers/Tomcat v7.0 Server at localhost-config/context.xml* in Eclipse.

The file context.xml is part of the OSGP/Config repo. This repo has been cloned to *~/Sources/Config* by the installation-script. The context.xml file can be found in the *tomcat* folder of the repo.

A developer needs to open this file and open the *Servers/Tomcat v7.0 Server at localhost-config/context.xml* file in Eclipse.
For each software component there are several lines of XML that need to be added to the *Servers/Tomcat v7.0 Server at localhost-config/context.xml* file in order to resolve the locations of properties files.

The two screenshots of section3.3.14 show the files in a text-editor and in Eclipse.
@Sander3003 Perhaps you would like to add a description to that section?

**Comment by Sander3003** [comment]
I'm working on a pull request ;)

**Comment by Sander3003** [comment]
Fixed
