### ISSUE TITLE
Fix gitbook cover

### ISSUE THREAD

**Issue by Sander3003** [OSGP/Documentation#8]
The current gitbook cover does not meet the Gitbook cover requirements. @EmmaKoster will fix this one day.

**Comment by Sander3003** [comment]
See this help page: gitbook format for cover http://help.gitbook.com/format/cover.html

**Comment by kevinsmeets** [comment]
The current status of this issue is:

- the file 'cover.jpg' has been changed and has the proper dimensions, so this normai sized version is OK
- the file 'cover_small.jpg' has not been changed, the dimensions are OK, but the image is not equal to the normal sized version
- the file 'Book-cover.jpg' is not needed anymore and can be removed

For now the cover images are OK, therefore this issue is closed for now. Feel free to re-open this issue to discus the cover images.
